//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmbracoODS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Global
    {
        public string GlobalKey { get; set; }
        public string GlobalValue { get; set; }
    }
}
