//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmbracoODS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IAPWebReportsEntities : DbContext
    {
        public IAPWebReportsEntities()
            : base("name=IAPWebReportsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Global> Globals { get; set; }
    
        public virtual int Rpt_HeadcountByCollegeRaceAndGender_EPM_EF(string censusKey, string acadCareer, string planCollege)
        {
            var censusKeyParameter = censusKey != null ?
                new ObjectParameter("censusKey", censusKey) :
                new ObjectParameter("censusKey", typeof(string));
    
            var acadCareerParameter = acadCareer != null ?
                new ObjectParameter("acadCareer", acadCareer) :
                new ObjectParameter("acadCareer", typeof(string));
    
            var planCollegeParameter = planCollege != null ?
                new ObjectParameter("planCollege", planCollege) :
                new ObjectParameter("planCollege", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Rpt_HeadcountByCollegeRaceAndGender_EPM_EF", censusKeyParameter, acadCareerParameter, planCollegeParameter);
        }
    
        public virtual ObjectResult<GetRecentPrelimFallTerms_EPM_Result> GetRecentPrelimFallTerms_EPM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRecentPrelimFallTerms_EPM_Result>("GetRecentPrelimFallTerms_EPM");
        }
    
        public virtual int GetCPCollegeListingByCensusKeyAndCareer_EPM(string censusKey, string acadCareer)
        {
            var censusKeyParameter = censusKey != null ?
                new ObjectParameter("censusKey", censusKey) :
                new ObjectParameter("censusKey", typeof(string));
    
            var acadCareerParameter = acadCareer != null ?
                new ObjectParameter("acadCareer", acadCareer) :
                new ObjectParameter("acadCareer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetCPCollegeListingByCensusKeyAndCareer_EPM", censusKeyParameter, acadCareerParameter);
        }
    
        public virtual int GetDCollegeListingByAcadYear_EPM(string acadYear)
        {
            var acadYearParameter = acadYear != null ?
                new ObjectParameter("acadYear", acadYear) :
                new ObjectParameter("acadYear", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDCollegeListingByAcadYear_EPM", acadYearParameter);
        }
    
        public virtual ObjectResult<Rpt_ClassSizeSummary_TermChoices_Result> Rpt_ClassSizeSummary_TermChoices()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rpt_ClassSizeSummary_TermChoices_Result>("Rpt_ClassSizeSummary_TermChoices");
        }
    
        public virtual ObjectResult<GetRecentFallAndSpringTerms_EPM_Result> GetRecentFallAndSpringTerms_EPM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRecentFallAndSpringTerms_EPM_Result>("GetRecentFallAndSpringTerms_EPM");
        }
    
        public virtual ObjectResult<string> GetRecentAnnualFTEYears_EPM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetRecentAnnualFTEYears_EPM");
        }
    
        public virtual ObjectResult<Rpt_AppliedAdmittedEnrolled_EPM_TermChoices_Result1> Rpt_AppliedAdmittedEnrolled_EPM_TermChoices()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rpt_AppliedAdmittedEnrolled_EPM_TermChoices_Result1>("Rpt_AppliedAdmittedEnrolled_EPM_TermChoices");
        }
    }
}
