//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "e57e613babf79c97")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.2")]

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Home</summary>
	[PublishedContentModel("home")]
	public partial class Home : PublishedContentModel, IGlobalControls, ITitleControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "home";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Website Name
		///</summary>
		[ImplementPropertyType("websiteName")]
		public string WebsiteName
		{
			get { return Umbraco.Web.PublishedContentModels.GlobalControls.GetWebsiteName(this); }
		}

		///<summary>
		/// Main Content: Enter the main content
		///</summary>
		[ImplementPropertyType("mainContent")]
		public IHtmlString MainContent
		{
			get { return Umbraco.Web.PublishedContentModels.TitleControls.GetMainContent(this); }
		}

		///<summary>
		/// Subtitle: Enter the subtitle
		///</summary>
		[ImplementPropertyType("subtitle")]
		public IHtmlString Subtitle
		{
			get { return Umbraco.Web.PublishedContentModels.TitleControls.GetSubtitle(this); }
		}

		///<summary>
		/// Title: Enter the title of the page, otherwise page name will be used
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return Umbraco.Web.PublishedContentModels.TitleControls.GetTitle(this); }
		}
	}

	/// <summary>StudentProfile</summary>
	[PublishedContentModel("studentProfile")]
	public partial class StudentProfile : PublishedContentModel, IGeneralControls, ITitleControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "studentProfile";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public StudentProfile(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<StudentProfile, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Top Menu Item
		///</summary>
		[ImplementPropertyType("topMenuItem")]
		public bool TopMenuItem
		{
			get { return Umbraco.Web.PublishedContentModels.GeneralControls.GetTopMenuItem(this); }
		}

		///<summary>
		/// Main Content: Enter the main content
		///</summary>
		[ImplementPropertyType("mainContent")]
		public IHtmlString MainContent
		{
			get { return Umbraco.Web.PublishedContentModels.TitleControls.GetMainContent(this); }
		}

		///<summary>
		/// Subtitle: Enter the subtitle
		///</summary>
		[ImplementPropertyType("subtitle")]
		public IHtmlString Subtitle
		{
			get { return Umbraco.Web.PublishedContentModels.TitleControls.GetSubtitle(this); }
		}

		///<summary>
		/// Title: Enter the title of the page, otherwise page name will be used
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return Umbraco.Web.PublishedContentModels.TitleControls.GetTitle(this); }
		}
	}

	/// <summary>Report List</summary>
	[PublishedContentModel("reportList")]
	public partial class ReportList : PublishedContentModel, IGeneralControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "reportList";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ReportList(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ReportList, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Top Menu Item
		///</summary>
		[ImplementPropertyType("topMenuItem")]
		public bool TopMenuItem
		{
			get { return Umbraco.Web.PublishedContentModels.GeneralControls.GetTopMenuItem(this); }
		}
	}

	// Mixin content Type 1073 with alias "titleControls"
	/// <summary>Title Controls</summary>
	public partial interface ITitleControls : IPublishedContent
	{
		/// <summary>Main Content</summary>
		IHtmlString MainContent { get; }

		/// <summary>Subtitle</summary>
		IHtmlString Subtitle { get; }

		/// <summary>Title</summary>
		string Title { get; }
	}

	/// <summary>Title Controls</summary>
	[PublishedContentModel("titleControls")]
	public partial class TitleControls : PublishedContentModel, ITitleControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "titleControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TitleControls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TitleControls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Main Content: Enter the main content
		///</summary>
		[ImplementPropertyType("mainContent")]
		public IHtmlString MainContent
		{
			get { return GetMainContent(this); }
		}

		/// <summary>Static getter for Main Content</summary>
		public static IHtmlString GetMainContent(ITitleControls that) { return that.GetPropertyValue<IHtmlString>("mainContent"); }

		///<summary>
		/// Subtitle: Enter the subtitle
		///</summary>
		[ImplementPropertyType("subtitle")]
		public IHtmlString Subtitle
		{
			get { return GetSubtitle(this); }
		}

		/// <summary>Static getter for Subtitle</summary>
		public static IHtmlString GetSubtitle(ITitleControls that) { return that.GetPropertyValue<IHtmlString>("subtitle"); }

		///<summary>
		/// Title: Enter the title of the page, otherwise page name will be used
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return GetTitle(this); }
		}

		/// <summary>Static getter for Title</summary>
		public static string GetTitle(ITitleControls that) { return that.GetPropertyValue<string>("title"); }
	}

	/// <summary>Decision Support</summary>
	[PublishedContentModel("decisionSupport")]
	public partial class DecisionSupport : PublishedContentModel, IGeneralControls, ITitleControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "decisionSupport";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DecisionSupport(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DecisionSupport, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Top Menu Item
		///</summary>
		[ImplementPropertyType("topMenuItem")]
		public bool TopMenuItem
		{
			get { return Umbraco.Web.PublishedContentModels.GeneralControls.GetTopMenuItem(this); }
		}

		///<summary>
		/// Main Content: Enter the main content
		///</summary>
		[ImplementPropertyType("mainContent")]
		public IHtmlString MainContent
		{
			get { return Umbraco.Web.PublishedContentModels.TitleControls.GetMainContent(this); }
		}

		///<summary>
		/// Subtitle: Enter the subtitle
		///</summary>
		[ImplementPropertyType("subtitle")]
		public IHtmlString Subtitle
		{
			get { return Umbraco.Web.PublishedContentModels.TitleControls.GetSubtitle(this); }
		}

		///<summary>
		/// Title: Enter the title of the page, otherwise page name will be used
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return Umbraco.Web.PublishedContentModels.TitleControls.GetTitle(this); }
		}
	}

	// Mixin content Type 1078 with alias "generalControls"
	/// <summary>General Controls</summary>
	public partial interface IGeneralControls : IPublishedContent
	{
		/// <summary>Top Menu Item</summary>
		bool TopMenuItem { get; }
	}

	/// <summary>General Controls</summary>
	[PublishedContentModel("generalControls")]
	public partial class GeneralControls : PublishedContentModel, IGeneralControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "generalControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GeneralControls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GeneralControls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Top Menu Item
		///</summary>
		[ImplementPropertyType("topMenuItem")]
		public bool TopMenuItem
		{
			get { return GetTopMenuItem(this); }
		}

		/// <summary>Static getter for Top Menu Item</summary>
		public static bool GetTopMenuItem(IGeneralControls that) { return that.GetPropertyValue<bool>("topMenuItem"); }
	}

	// Mixin content Type 1079 with alias "globalControls"
	/// <summary>Global Controls</summary>
	public partial interface IGlobalControls : IPublishedContent
	{
		/// <summary>Website Name</summary>
		string WebsiteName { get; }
	}

	/// <summary>Global Controls</summary>
	[PublishedContentModel("globalControls")]
	public partial class GlobalControls : PublishedContentModel, IGlobalControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "globalControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GlobalControls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GlobalControls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Website Name
		///</summary>
		[ImplementPropertyType("websiteName")]
		public string WebsiteName
		{
			get { return GetWebsiteName(this); }
		}

		/// <summary>Static getter for Website Name</summary>
		public static string GetWebsiteName(IGlobalControls that) { return that.GetPropertyValue<string>("websiteName"); }
	}

	/// <summary>Staff Member</summary>
	[PublishedContentModel("staffMember")]
	public partial class StaffMember : PublishedContentModel, IStaffMemberControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "staffMember";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public StaffMember(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<StaffMember, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Biography, Education, etc.
		///</summary>
		[ImplementPropertyType("biography")]
		public IHtmlString Biography
		{
			get { return Umbraco.Web.PublishedContentModels.StaffMemberControls.GetBiography(this); }
		}

		///<summary>
		/// Department
		///</summary>
		[ImplementPropertyType("department")]
		public string Department
		{
			get { return Umbraco.Web.PublishedContentModels.StaffMemberControls.GetDepartment(this); }
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("email")]
		public string Email
		{
			get { return Umbraco.Web.PublishedContentModels.StaffMemberControls.GetEmail(this); }
		}

		///<summary>
		/// Fax
		///</summary>
		[ImplementPropertyType("fax")]
		public string Fax
		{
			get { return Umbraco.Web.PublishedContentModels.StaffMemberControls.GetFax(this); }
		}

		///<summary>
		/// Full Name,: Academic Degree - optional
		///</summary>
		[ImplementPropertyType("fullName")]
		public string FullName
		{
			get { return Umbraco.Web.PublishedContentModels.StaffMemberControls.GetFullName(this); }
		}

		///<summary>
		/// Job Title
		///</summary>
		[ImplementPropertyType("jobTitle")]
		public string JobTitle
		{
			get { return Umbraco.Web.PublishedContentModels.StaffMemberControls.GetJobTitle(this); }
		}

		///<summary>
		/// Mail Code
		///</summary>
		[ImplementPropertyType("mailCode")]
		public string MailCode
		{
			get { return Umbraco.Web.PublishedContentModels.StaffMemberControls.GetMailCode(this); }
		}

		///<summary>
		/// Office
		///</summary>
		[ImplementPropertyType("office")]
		public string Office
		{
			get { return Umbraco.Web.PublishedContentModels.StaffMemberControls.GetOffice(this); }
		}

		///<summary>
		/// Phone
		///</summary>
		[ImplementPropertyType("phone")]
		public string Phone
		{
			get { return Umbraco.Web.PublishedContentModels.StaffMemberControls.GetPhone(this); }
		}

		///<summary>
		/// Photo
		///</summary>
		[ImplementPropertyType("photo")]
		public IPublishedContent Photo
		{
			get { return Umbraco.Web.PublishedContentModels.StaffMemberControls.GetPhoto(this); }
		}
	}

	/// <summary>Staff</summary>
	[PublishedContentModel("staff")]
	public partial class Staff : PublishedContentModel, IGeneralControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "staff";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Staff(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Staff, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Top Menu Item
		///</summary>
		[ImplementPropertyType("topMenuItem")]
		public bool TopMenuItem
		{
			get { return Umbraco.Web.PublishedContentModels.GeneralControls.GetTopMenuItem(this); }
		}
	}

	// Mixin content Type 1091 with alias "staffMemberControls"
	/// <summary>Staff Member Controls</summary>
	public partial interface IStaffMemberControls : IPublishedContent
	{
		/// <summary>Biography, Education, etc.</summary>
		IHtmlString Biography { get; }

		/// <summary>Department</summary>
		string Department { get; }

		/// <summary>Email</summary>
		string Email { get; }

		/// <summary>Fax</summary>
		string Fax { get; }

		/// <summary>Full Name,</summary>
		string FullName { get; }

		/// <summary>Job Title</summary>
		string JobTitle { get; }

		/// <summary>Mail Code</summary>
		string MailCode { get; }

		/// <summary>Office</summary>
		string Office { get; }

		/// <summary>Phone</summary>
		string Phone { get; }

		/// <summary>Photo</summary>
		IPublishedContent Photo { get; }
	}

	/// <summary>Staff Member Controls</summary>
	[PublishedContentModel("staffMemberControls")]
	public partial class StaffMemberControls : PublishedContentModel, IStaffMemberControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "staffMemberControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public StaffMemberControls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<StaffMemberControls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Biography, Education, etc.
		///</summary>
		[ImplementPropertyType("biography")]
		public IHtmlString Biography
		{
			get { return GetBiography(this); }
		}

		/// <summary>Static getter for Biography, Education, etc.</summary>
		public static IHtmlString GetBiography(IStaffMemberControls that) { return that.GetPropertyValue<IHtmlString>("biography"); }

		///<summary>
		/// Department
		///</summary>
		[ImplementPropertyType("department")]
		public string Department
		{
			get { return GetDepartment(this); }
		}

		/// <summary>Static getter for Department</summary>
		public static string GetDepartment(IStaffMemberControls that) { return that.GetPropertyValue<string>("department"); }

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("email")]
		public string Email
		{
			get { return GetEmail(this); }
		}

		/// <summary>Static getter for Email</summary>
		public static string GetEmail(IStaffMemberControls that) { return that.GetPropertyValue<string>("email"); }

		///<summary>
		/// Fax
		///</summary>
		[ImplementPropertyType("fax")]
		public string Fax
		{
			get { return GetFax(this); }
		}

		/// <summary>Static getter for Fax</summary>
		public static string GetFax(IStaffMemberControls that) { return that.GetPropertyValue<string>("fax"); }

		///<summary>
		/// Full Name,: Academic Degree - optional
		///</summary>
		[ImplementPropertyType("fullName")]
		public string FullName
		{
			get { return GetFullName(this); }
		}

		/// <summary>Static getter for Full Name,</summary>
		public static string GetFullName(IStaffMemberControls that) { return that.GetPropertyValue<string>("fullName"); }

		///<summary>
		/// Job Title
		///</summary>
		[ImplementPropertyType("jobTitle")]
		public string JobTitle
		{
			get { return GetJobTitle(this); }
		}

		/// <summary>Static getter for Job Title</summary>
		public static string GetJobTitle(IStaffMemberControls that) { return that.GetPropertyValue<string>("jobTitle"); }

		///<summary>
		/// Mail Code
		///</summary>
		[ImplementPropertyType("mailCode")]
		public string MailCode
		{
			get { return GetMailCode(this); }
		}

		/// <summary>Static getter for Mail Code</summary>
		public static string GetMailCode(IStaffMemberControls that) { return that.GetPropertyValue<string>("mailCode"); }

		///<summary>
		/// Office
		///</summary>
		[ImplementPropertyType("office")]
		public string Office
		{
			get { return GetOffice(this); }
		}

		/// <summary>Static getter for Office</summary>
		public static string GetOffice(IStaffMemberControls that) { return that.GetPropertyValue<string>("office"); }

		///<summary>
		/// Phone
		///</summary>
		[ImplementPropertyType("phone")]
		public string Phone
		{
			get { return GetPhone(this); }
		}

		/// <summary>Static getter for Phone</summary>
		public static string GetPhone(IStaffMemberControls that) { return that.GetPropertyValue<string>("phone"); }

		///<summary>
		/// Photo
		///</summary>
		[ImplementPropertyType("photo")]
		public IPublishedContent Photo
		{
			get { return GetPhoto(this); }
		}

		/// <summary>Static getter for Photo</summary>
		public static IPublishedContent GetPhoto(IStaffMemberControls that) { return that.GetPropertyValue<IPublishedContent>("photo"); }
	}

	// Mixin content Type 1100 with alias "dataDictionaryControls"
	/// <summary>Item Controls</summary>
	public partial interface IDataDictionaryControls : IPublishedContent
	{
		/// <summary>Definition Comments</summary>
		IHtmlString DefinitionComments { get; }

		/// <summary>Description</summary>
		IHtmlString Description { get; }

		/// <summary>Interpretation / Usage Notes</summary>
		IHtmlString InterpretationUsageNotes { get; }

		/// <summary>Potential Values</summary>
		IHtmlString PotentialValues { get; }

		/// <summary>See Also</summary>
		IHtmlString SeeAlso { get; }

		/// <summary>Source Description</summary>
		IHtmlString SourceDescription { get; }

		/// <summary>Source System</summary>
		string SourceSystem { get; }

		/// <summary>Status</summary>
		string Status { get; }
	}

	/// <summary>Item Controls</summary>
	[PublishedContentModel("dataDictionaryControls")]
	public partial class DataDictionaryControls : PublishedContentModel, IDataDictionaryControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "dataDictionaryControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DataDictionaryControls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DataDictionaryControls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Definition Comments
		///</summary>
		[ImplementPropertyType("definitionComments")]
		public IHtmlString DefinitionComments
		{
			get { return GetDefinitionComments(this); }
		}

		/// <summary>Static getter for Definition Comments</summary>
		public static IHtmlString GetDefinitionComments(IDataDictionaryControls that) { return that.GetPropertyValue<IHtmlString>("definitionComments"); }

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public IHtmlString Description
		{
			get { return GetDescription(this); }
		}

		/// <summary>Static getter for Description</summary>
		public static IHtmlString GetDescription(IDataDictionaryControls that) { return that.GetPropertyValue<IHtmlString>("description"); }

		///<summary>
		/// Interpretation / Usage Notes
		///</summary>
		[ImplementPropertyType("interpretationUsageNotes")]
		public IHtmlString InterpretationUsageNotes
		{
			get { return GetInterpretationUsageNotes(this); }
		}

		/// <summary>Static getter for Interpretation / Usage Notes</summary>
		public static IHtmlString GetInterpretationUsageNotes(IDataDictionaryControls that) { return that.GetPropertyValue<IHtmlString>("interpretationUsageNotes"); }

		///<summary>
		/// Potential Values
		///</summary>
		[ImplementPropertyType("potentialValues")]
		public IHtmlString PotentialValues
		{
			get { return GetPotentialValues(this); }
		}

		/// <summary>Static getter for Potential Values</summary>
		public static IHtmlString GetPotentialValues(IDataDictionaryControls that) { return that.GetPropertyValue<IHtmlString>("potentialValues"); }

		///<summary>
		/// See Also
		///</summary>
		[ImplementPropertyType("seeAlso")]
		public IHtmlString SeeAlso
		{
			get { return GetSeeAlso(this); }
		}

		/// <summary>Static getter for See Also</summary>
		public static IHtmlString GetSeeAlso(IDataDictionaryControls that) { return that.GetPropertyValue<IHtmlString>("seeAlso"); }

		///<summary>
		/// Source Description
		///</summary>
		[ImplementPropertyType("sourceDescription")]
		public IHtmlString SourceDescription
		{
			get { return GetSourceDescription(this); }
		}

		/// <summary>Static getter for Source Description</summary>
		public static IHtmlString GetSourceDescription(IDataDictionaryControls that) { return that.GetPropertyValue<IHtmlString>("sourceDescription"); }

		///<summary>
		/// Source System
		///</summary>
		[ImplementPropertyType("sourceSystem")]
		public string SourceSystem
		{
			get { return GetSourceSystem(this); }
		}

		/// <summary>Static getter for Source System</summary>
		public static string GetSourceSystem(IDataDictionaryControls that) { return that.GetPropertyValue<string>("sourceSystem"); }

		///<summary>
		/// Status
		///</summary>
		[ImplementPropertyType("status")]
		public string Status
		{
			get { return GetStatus(this); }
		}

		/// <summary>Static getter for Status</summary>
		public static string GetStatus(IDataDictionaryControls that) { return that.GetPropertyValue<string>("status"); }
	}

	/// <summary>Data Dictionary Home</summary>
	[PublishedContentModel("dataDictionary")]
	public partial class DataDictionary : PublishedContentModel, IDataDictionaryGeneralControls, IDataDictionaryLinkControls, IGeneralControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "dataDictionary";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DataDictionary(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DataDictionary, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public IHtmlString Description
		{
			get { return Umbraco.Web.PublishedContentModels.DataDictionaryGeneralControls.GetDescription(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return Umbraco.Web.PublishedContentModels.DataDictionaryGeneralControls.GetTitle(this); }
		}

		///<summary>
		/// Links to the Terms
		///</summary>
		[ImplementPropertyType("linksToTheTerms")]
		public Umbraco.Web.Models.RelatedLinks LinksToTheTerms
		{
			get { return Umbraco.Web.PublishedContentModels.DataDictionaryLinkControls.GetLinksToTheTerms(this); }
		}

		///<summary>
		/// Top Menu Item
		///</summary>
		[ImplementPropertyType("topMenuItem")]
		public bool TopMenuItem
		{
			get { return Umbraco.Web.PublishedContentModels.GeneralControls.GetTopMenuItem(this); }
		}
	}

	/// <summary>Item</summary>
	[PublishedContentModel("dataDictionaryItem")]
	public partial class DataDictionaryItem : PublishedContentModel, IDataDictionaryControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "dataDictionaryItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DataDictionaryItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DataDictionaryItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Definition Comments
		///</summary>
		[ImplementPropertyType("definitionComments")]
		public IHtmlString DefinitionComments
		{
			get { return Umbraco.Web.PublishedContentModels.DataDictionaryControls.GetDefinitionComments(this); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public IHtmlString Description
		{
			get { return Umbraco.Web.PublishedContentModels.DataDictionaryControls.GetDescription(this); }
		}

		///<summary>
		/// Interpretation / Usage Notes
		///</summary>
		[ImplementPropertyType("interpretationUsageNotes")]
		public IHtmlString InterpretationUsageNotes
		{
			get { return Umbraco.Web.PublishedContentModels.DataDictionaryControls.GetInterpretationUsageNotes(this); }
		}

		///<summary>
		/// Potential Values
		///</summary>
		[ImplementPropertyType("potentialValues")]
		public IHtmlString PotentialValues
		{
			get { return Umbraco.Web.PublishedContentModels.DataDictionaryControls.GetPotentialValues(this); }
		}

		///<summary>
		/// See Also
		///</summary>
		[ImplementPropertyType("seeAlso")]
		public IHtmlString SeeAlso
		{
			get { return Umbraco.Web.PublishedContentModels.DataDictionaryControls.GetSeeAlso(this); }
		}

		///<summary>
		/// Source Description
		///</summary>
		[ImplementPropertyType("sourceDescription")]
		public IHtmlString SourceDescription
		{
			get { return Umbraco.Web.PublishedContentModels.DataDictionaryControls.GetSourceDescription(this); }
		}

		///<summary>
		/// Source System
		///</summary>
		[ImplementPropertyType("sourceSystem")]
		public string SourceSystem
		{
			get { return Umbraco.Web.PublishedContentModels.DataDictionaryControls.GetSourceSystem(this); }
		}

		///<summary>
		/// Status
		///</summary>
		[ImplementPropertyType("status")]
		public string Status
		{
			get { return Umbraco.Web.PublishedContentModels.DataDictionaryControls.GetStatus(this); }
		}
	}

	// Mixin content Type 1105 with alias "dataDictionaryLinkControls"
	/// <summary>Link Controls</summary>
	public partial interface IDataDictionaryLinkControls : IPublishedContent
	{
		/// <summary>Links to the Terms</summary>
		Umbraco.Web.Models.RelatedLinks LinksToTheTerms { get; }
	}

	/// <summary>Link Controls</summary>
	[PublishedContentModel("dataDictionaryLinkControls")]
	public partial class DataDictionaryLinkControls : PublishedContentModel, IDataDictionaryLinkControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "dataDictionaryLinkControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DataDictionaryLinkControls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DataDictionaryLinkControls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Links to the Terms
		///</summary>
		[ImplementPropertyType("linksToTheTerms")]
		public Umbraco.Web.Models.RelatedLinks LinksToTheTerms
		{
			get { return GetLinksToTheTerms(this); }
		}

		/// <summary>Static getter for Links to the Terms</summary>
		public static Umbraco.Web.Models.RelatedLinks GetLinksToTheTerms(IDataDictionaryLinkControls that) { return that.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("linksToTheTerms"); }
	}

	// Mixin content Type 1110 with alias "dataDictionaryGeneralControls"
	/// <summary>Data Dictionary General Controls</summary>
	public partial interface IDataDictionaryGeneralControls : IPublishedContent
	{
		/// <summary>Description</summary>
		IHtmlString Description { get; }

		/// <summary>Title</summary>
		string Title { get; }
	}

	/// <summary>Data Dictionary General Controls</summary>
	[PublishedContentModel("dataDictionaryGeneralControls")]
	public partial class DataDictionaryGeneralControls : PublishedContentModel, IDataDictionaryGeneralControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "dataDictionaryGeneralControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DataDictionaryGeneralControls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DataDictionaryGeneralControls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public IHtmlString Description
		{
			get { return GetDescription(this); }
		}

		/// <summary>Static getter for Description</summary>
		public static IHtmlString GetDescription(IDataDictionaryGeneralControls that) { return that.GetPropertyValue<IHtmlString>("description"); }

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return GetTitle(this); }
		}

		/// <summary>Static getter for Title</summary>
		public static string GetTitle(IDataDictionaryGeneralControls that) { return that.GetPropertyValue<string>("title"); }
	}

	/// <summary>Subject Area</summary>
	[PublishedContentModel("dataDictionarySubjectArea")]
	public partial class DataDictionarySubjectArea : PublishedContentModel, IDataDictionaryGeneralControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "dataDictionarySubjectArea";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DataDictionarySubjectArea(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DataDictionarySubjectArea, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public IHtmlString Description
		{
			get { return Umbraco.Web.PublishedContentModels.DataDictionaryGeneralControls.GetDescription(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return Umbraco.Web.PublishedContentModels.DataDictionaryGeneralControls.GetTitle(this); }
		}
	}

	/// <summary>Item Group</summary>
	[PublishedContentModel("dataDictionaryItemGroup")]
	public partial class DataDictionaryItemGroup : PublishedContentModel, IDataDictionaryGeneralControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "dataDictionaryItemGroup";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DataDictionaryItemGroup(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DataDictionaryItemGroup, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public IHtmlString Description
		{
			get { return Umbraco.Web.PublishedContentModels.DataDictionaryGeneralControls.GetDescription(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return Umbraco.Web.PublishedContentModels.DataDictionaryGeneralControls.GetTitle(this); }
		}
	}

	/// <summary>Generic Page</summary>
	[PublishedContentModel("sideMenusPage")]
	public partial class SideMenusPage : PublishedContentModel, IGeneralControls, IReportControl, ITitleControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "sideMenusPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SideMenusPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SideMenusPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Top Menu Item
		///</summary>
		[ImplementPropertyType("topMenuItem")]
		public bool TopMenuItem
		{
			get { return Umbraco.Web.PublishedContentModels.GeneralControls.GetTopMenuItem(this); }
		}

		///<summary>
		/// Report
		///</summary>
		[ImplementPropertyType("reportDbName")]
		public string ReportDbName
		{
			get { return Umbraco.Web.PublishedContentModels.ReportControl.GetReportDbName(this); }
		}

		///<summary>
		/// Years Back
		///</summary>
		[ImplementPropertyType("yearsBack")]
		public int YearsBack
		{
			get { return Umbraco.Web.PublishedContentModels.ReportControl.GetYearsBack(this); }
		}

		///<summary>
		/// Main Content: Enter the main content
		///</summary>
		[ImplementPropertyType("mainContent")]
		public IHtmlString MainContent
		{
			get { return Umbraco.Web.PublishedContentModels.TitleControls.GetMainContent(this); }
		}

		///<summary>
		/// Subtitle: Enter the subtitle
		///</summary>
		[ImplementPropertyType("subtitle")]
		public IHtmlString Subtitle
		{
			get { return Umbraco.Web.PublishedContentModels.TitleControls.GetSubtitle(this); }
		}

		///<summary>
		/// Title: Enter the title of the page, otherwise page name will be used
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return Umbraco.Web.PublishedContentModels.TitleControls.GetTitle(this); }
		}
	}

	/// <summary>Advanced Search</summary>
	[PublishedContentModel("advancedSearch")]
	public partial class AdvancedSearch : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "advancedSearch";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AdvancedSearch(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AdvancedSearch, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Simple Search</summary>
	[PublishedContentModel("simpleSearch")]
	public partial class SimpleSearch : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "simpleSearch";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SimpleSearch(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SimpleSearch, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	// Mixin content Type 1152 with alias "reportControl"
	/// <summary>Report Control</summary>
	public partial interface IReportControl : IPublishedContent
	{
		/// <summary>Report</summary>
		string ReportDbName { get; }

		/// <summary>Years Back</summary>
		int YearsBack { get; }
	}

	/// <summary>Report Control</summary>
	[PublishedContentModel("reportControl")]
	public partial class ReportControl : PublishedContentModel, IReportControl
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "reportControl";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ReportControl(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ReportControl, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Report
		///</summary>
		[ImplementPropertyType("reportDbName")]
		public string ReportDbName
		{
			get { return GetReportDbName(this); }
		}

		/// <summary>Static getter for Report</summary>
		public static string GetReportDbName(IReportControl that) { return that.GetPropertyValue<string>("reportDbName"); }

		///<summary>
		/// Years Back
		///</summary>
		[ImplementPropertyType("yearsBack")]
		public int YearsBack
		{
			get { return GetYearsBack(this); }
		}

		/// <summary>Static getter for Years Back</summary>
		public static int GetYearsBack(IReportControl that) { return that.GetPropertyValue<int>("yearsBack"); }
	}

	// Mixin content Type 1470 with alias "prettyLinkControls"
	/// <summary>Pretty Link Controls</summary>
	public partial interface IPrettyLinkControls : IPublishedContent
	{
		/// <summary>Link Target</summary>
		Umbraco.Web.Models.RelatedLinks LinkTarget { get; }
	}

	/// <summary>Pretty Link Controls</summary>
	[PublishedContentModel("prettyLinkControls")]
	public partial class PrettyLinkControls : PublishedContentModel, IPrettyLinkControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "prettyLinkControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PrettyLinkControls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PrettyLinkControls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Link Target: Enter the external link here
		///</summary>
		[ImplementPropertyType("linkTarget")]
		public Umbraco.Web.Models.RelatedLinks LinkTarget
		{
			get { return GetLinkTarget(this); }
		}

		/// <summary>Static getter for Link Target</summary>
		public static Umbraco.Web.Models.RelatedLinks GetLinkTarget(IPrettyLinkControls that) { return that.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("linkTarget"); }
	}

	/// <summary>Pretty Link</summary>
	[PublishedContentModel("prettyLink")]
	public partial class PrettyLink : PublishedContentModel, IPrettyLinkControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "prettyLink";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PrettyLink(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PrettyLink, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Link Target: Enter the external link here
		///</summary>
		[ImplementPropertyType("linkTarget")]
		public Umbraco.Web.Models.RelatedLinks LinkTarget
		{
			get { return Umbraco.Web.PublishedContentModels.PrettyLinkControls.GetLinkTarget(this); }
		}
	}

	/// <summary>Login</summary>
	[PublishedContentModel("login")]
	public partial class Login : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "login";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Login(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Login, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public string UmbracoFile
		{
			get { return this.GetPropertyValue<string>("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Title: Position Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}
